export const contentTypeMapToFileExtension = {
  pdf: "application/pdf",
  zip: "application/zip",
  mp3: "audio/mpeg",
  wav: "audio/wav",
  ogg: "audio/ogg",
  mp4: "video/mp4",
  avi: "video/avi",
  mov: "video/quicktime",  
  ogv: "video/ogg",
  webv: "video/webm",
  doc: "application/msword",
  docx: "application/msword",
  xls: "application/vnd.ms-excel",
  xlsx: "application/vnd.ms-excel",
  ppt: "application/vnd.ms-powerpoint",
  pptx: "application/vnd.ms-powerpoint",
  png: "image/png",
  jpeg: "image/jpeg",
  gif: "image/gif",
  bmp: "image/bmp",
  rar: "application/x-rar-compressed",
  tiff: "image/tiff",
  webp: "image/webp",
};

